baseURL = "https://www.gillesmaire.com"
languageCode = "fr-FR"
title = "Gilles Maire Dev + teaching"
theme = "resume"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true
defaultContentLanguage = 'fr'

[params]
address = "Paris, France"
email = "gilles@gillesmaire.com"
favicon = "/favicon.ico"
firstName = "Gilles"
lastName = "Maire"
phone = "+607-990-655"
profileImage = "img/GillesMaire.png"
showQr = true
showContact = true
showBoards  = false
showCertifications = false
showSocializations = true
sections = ["skills","publications","creations","contributions","experience","education","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/gilles-maire-38792771/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/gillesmaire"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/gillesmaire"
    icon = "keybase"
    
[[params.handles]]
    name = "Mastodon"
    link = "https://mastodon.social/@GilesDesJetes"
    icon = "mastodon"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
