baseURL = "https://sitegillesmaire.pages.dev/"
languageCode = "fr-FR"
title = "Gilles Maire Dev + Teaching"
theme = "hugo-resume"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true
defaultContentLanguage = 'fr'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
address = "Paris, France 68, rue Leibniz SIRET: 50072904100011"
email = "gilles@gillesmaire.com"
favicon = "/favicon.ico"
firstName = "Gilles"
lastName = "Maire"
phone = "+33 607-990-655"
profileImage = "img/GillesMaire.png"
showQr = true
showContact = true
showBoards  = false
showCertifications = false
showSocializations = true
sections = ["skills","experience","education","publications","creations","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/gilles-maire-38792771/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/gillesmaire"

[[params.handles]]
    name="SourceForge"
    link="https://sourceforge.net/u/gillesm/profile"
    clas="sourceforge"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/gmaire"
    icon = "keybase"
    
[[params.handles]]
    name = "Mastodon"
    link = "https://mastodon.social/@GilesDesJetes"
    icon = "mastodon"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"


[outputFormats]
  [outputFormats.CSS]
    mediaType = "text/css"

