[build]
  command = "hugo --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.146.5"

[build.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/tiki-index.php?page=home"
  to = "/"
  status = 301
  force = true
